version: "3.8"

services:
  app:
    container_name: dorayaki-store
    image: dorayaki-store
    build:
      context: .
    volumes:
      - ./src:/app/src
    ports:
      - 3000:3000
    env_file: .env
    command: npm start